
application:
  name: name=chatter

server:
  port: 8888

spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/my_erp
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect